In [1]:
import numpy as np
import pandas as pd

In [2]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [3]:
print(a1)

[1 2 3 4]


In [4]:
type(a1)

numpy.ndarray

In [5]:
type(a1[0])

numpy.int32

In [7]:
a1.shape

(4,)

In [8]:
type(a1.shape)

tuple

In [10]:
a2 = np.array([[1,2,3], [3,4,5], [5,6,7]])

In [11]:
print(a2)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [12]:
a2.shape

(3, 3)

In [13]:
a2.ndim

2

In [14]:
np.ndim(a2)

2

In [17]:
a3 = np.array(
[
    [1,2,3],
    [3, [4], 8],
    [5,6,7]
], dtype=object
)

In [18]:
print(a3)

[[1 2 3]
 [3 list([4]) 8]
 [5 6 7]]


In [19]:
type(a3)

numpy.ndarray

In [20]:
a3.ndim

2

In [21]:
a4 = np.array([[[1,3,3]]])

In [22]:
a4.ndim

3

In [23]:
a5 = np.array(
    [
        [1,2,3],
        [3,5,7],
        [15, 65, 43],
        [66, 33,22],
        [7, 9, 0],
        [12,45,66]
    ]
)

In [24]:
a5.shape

(6, 3)

In [29]:
a5.shape = (9,2)

In [30]:
a5

array([[ 1,  2],
       [ 3,  3],
       [ 5,  7],
       [15, 65],
       [43, 66],
       [33, 22],
       [ 7,  9],
       [ 0, 12],
       [45, 66]])

In [36]:
a6 = a5.copy()
a6

array([[ 1,  2],
       [ 3,  3],
       [ 5,  7],
       [15, 65],
       [43, 66],
       [33, 22],
       [ 7,  9],
       [ 0, 12],
       [45, 66]])

In [37]:
a5[0,0] = 1001
a5

array([[1001,    2],
       [   3,    3],
       [   5,    7],
       [  15,   65],
       [  43,   66],
       [  33,   22],
       [   7,    9],
       [   0,   12],
       [  45,   66]])

In [38]:
a6

array([[ 1,  2],
       [ 3,  3],
       [ 5,  7],
       [15, 65],
       [43, 66],
       [33, 22],
       [ 7,  9],
       [ 0, 12],
       [45, 66]])

In [31]:
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
b2 = np.ones( (4,3), dtype=int)
b2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [35]:
b3 = np.zeros( (3, 4), dtype=int)
b3

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [40]:
c1 = np.identity(4, dtype=int)
c1

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [41]:
c2 = np.eye(2,3,1, dtype=int)
c2

array([[0, 1, 0],
       [0, 0, 1]])